module.exports = {
  domain: process.env.MYDOMAIN || "http://localhost:3000",
  coloronlydark: true,
  onlygray: false,
  name: "M. Husni Nur Fadillah",
  image: "/img/husni-formal-removebg-preview.png",
  profile: "/img/husni-formal-removebg-preview.png",
  thumbnail: "/img/thumbnail.png",
  blogthumbnail: "/img/blog-thumbnail.png",
  role: "Backend Engineer Wannabe",
  description:
    "A mathematics graduate who has a passion for the field of software engineering, especially backend development.",
  resume: "https://resume.io/r/iuDuhDJJn",
  socials: [
    { href: "https://github.com/husfuu", label: "Github" },
    { href: "https://twitter.com/tanakafuu", label: "Twitter" },
    {
      href: "https://www.linkedin.com/in/muhammad-husni-nur-fadillah/",
      label: "Linkedin",
    },
    { href: "https://polywork.com/husfuu", label: "Polywork" },
  ],
  navlinks: [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/blog", label: "Blog" },
    // { href: "/resources", label: "Resources" },
    // { href: "/snippets", label: "Snippets" },
    { href: "/projects", label: "Projects" },
  ],
  about: [
    "Hello, my name is Husni. I have a degree in mathematics and am passionate about software engineering, especially backend development.",
    "I have experience developing REST APIs with NodeJS and Golang. Additionally, I develop the front end using ReactJS and Tailwind CSS.",
    "I have experience studying at several institutions, such as Binar Academy through the Kampus Merdeka program, Digitalent Scholarship from Kominfo, and Data Science Bootcamp from the Data Science Indonesia Community.",
    "I've built and contributed to several projects, although they still need to be developed.",
  ],
  experiences: [
    {
      startTime: "August 2021",
      endTime: "Februari 2022",
      role: "Fullstack Web Development",
      company: "Binar Academy",
      description: "Studi Independen Kampus Merdeka Batch 1",
    },
    {
      startTime: "December 2022",
      endTime: "March 2022",
      role: "Data Science",
      company: "Data Science Indonesia",
      description: "Studi Independen Kampus Merdeka Batch 1",
    },
  ],
  educations: [
    {
      startTime: "August 2022",
      endTime: "Now",
      role: "Java Backend Engineer",
      company: "Synrgy Academy",
      description: "Synrgy Academy Scholarship by BCA x Binar Academy Batch 5",
    },
    {
      startTime: "August 2018",
      endTime: "August 2022",
      role: "Mathematics",
      company: "Universitas Lambung Mangkurat",
      description: "Take machine learning as a field of study",
    },
  ],
  projects: [
    {
      title: "Topup Gimang - Server",
      image: "",
      url: "https://corona.zekhoi.my.id/",
      description: "A website that track corona virus every country.",
      stacks: ["nodejs", "express", "vercel"],
    },
    {
      title: "Topup Gimang - Dashboard",
      image: "",
      url: "https://zekhoi.my.id/",
      description:
        "My Personal website version 2 build with NextJS and Tailwind.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "GoGram - REST API",
      image: "",
      url: "https://discord.com/api/oauth2/authorize?client_id=935198224761896980&permissions=8&scope=bot",
      description: "A basic discord bot, it can speak.",
      stacks: ["nodejs", "javascript"],
    },
    {
      title: "BookShelf - REST API",
      image: "",
      url: "https://seminar.zekhoi.my.id/",
      description: "Seminar Schedule Event Calendar from Matematika FMIPA ULM.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "Go-biodata-CLI - CLI APP",
      image: "",
      url: "https://booku.zekhoi.my.id/",
      description: "Technical test result.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
  ],
  colors: {
    primary: {
      50: "#F0F9FF",
      100: "#DBF1FF",
      200: "#B8E2FF",
      300: "#8AD0FF",
      400: "#52BAFF",
      500: "#0099FF",
      600: "#008AE6",
      700: "#007ACC",
      800: "#0065A8",
      900: "#00497A",
    },
    success: {
      50: "#EEFCF6",
      100: "#DCF9EE",
      200: "#B0F2D8",
      300: "#80EAC0",
      400: "#3FDF9F",
      500: "#22CC88",
      600: "#1FB87A",
      700: "#1BA26C",
      800: "#17875A",
      900: "#106040",
    },
    danger: {
      50: "#FFF5F8",
      100: "#FFE5EE",
      200: "#FFCCDD",
      300: "#FFA8C5",
      400: "#FF7AA7",
      500: "#FF0055",
      600: "#EB004E",
      700: "#CC0044",
      800: "#AD003A",
      900: "#750027",
    },
    warning: {
      50: "#FFF8EB",
      100: "#FFF3DB",
      200: "#FFE4AD",
      300: "#FFD480",
      400: "#FFC247",
      500: "#FFAA00",
      600: "#E69900",
      700: "#CC8800",
      800: "#A87000",
      900: "#7A5200",
    },
  },
};
